import type { NextPage } from "next"
import Head from "next/head"
import { Button, Flex, FormControl, FormLabel, Stack } from "@chakra-ui/react"
import { Input } from "../components/Form/Input"

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100vw" h="100vh" alignItems="center" justifyContent="center">
        <Flex
          as="form"
          width="100%"
          maxWidth={360}
          bg="gray.800"
          p={8}
          borderRadius={8}
          flexDir={"column"}
        >
          <Stack spacing={4}>
            <Input name="email" label="Email" type={"email"} />
            <Input name="password" type={"password"} label="Password" />
          </Stack>
          <Button type="submit" mt={6} colorScheme={"pink"}>
            Sign In
          </Button>
        </Flex>
      </Flex>
    </>
  )
}

export default SignIn
